# Generated by Django 5.1.1 on 2024-09-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_category_supplier_alter_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('hope', 'Hope'), ('however', 'However'), ('attack', 'Attack'), ('citizen', 'Citizen'), ('type', 'Type')], max_length=100),
        ),
    ]
